# Generated by Django 3.0.7 on 2020-06-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('featureImage', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=200)),
                ('bio', models.TextField()),
            ],
        ),
    ]
