# Generated by Django 3.0.7 on 2020-07-10 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post_urlslug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='urlSlug',
        ),
    ]
