# Generated by Django 3.0.7 on 2020-07-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_post_urlslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='urlSlug',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
