# Generated by Django 3.0.7 on 2020-07-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_post_urlslug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='urlSlug',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
