# Generated by Django 3.0.7 on 2020-06-21 18:45

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('socialLinks', jsonfield.fields.JSONField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='bio',
        ),
        migrations.AddField(
            model_name='post',
            name='areCommentsEnabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Writer'),
        ),
    ]
