# Generated by Django 3.0.7 on 2020-07-10 22:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200621_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='urlSlug',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
